export const reports = [
  {
    folder: "Data Source Release",
    icon: "mdi-sigma-lower",
    name: "Data Quality",
    routeName: "dataQuality",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-chart-line",
    name: "Person",
    routeName: "person",
  },
  {
    folder: "Data Network",
    icon: "mdi-database-search",
    name: "Data Source Feasibility",
    routeName: "feasibility",
  },
  {
    folder: "Data Network",
    icon: "mdi-speedometer",
    name: "Network Performance",
    routeName: "networkPerformance",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-chart-line",
    name: "Data Density",
    routeName: "dataDensity",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-chart-line",
    name: "Observation Period",
    routeName: "observationPeriod",
  },
  {
    folder: "Data Source",
    name: "Data Quality History",
    routeName: "dataQualityHistory",
  },
  {
    folder: "Data Source",
    name: "Data Source Overview",
    routeName: "dataSourceOverview",
  },
  {
    folder: "Data Source",
    name: "Domain Continuity",
    routeName: "domainContinuity",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Conditions",
    routeName: "domainTable",
    domain: "condition_occurrence",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Condition Eras",
    routeName: "domainTable",
    domain: "condition_era",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Drugs",
    routeName: "domainTable",
    domain: "drug_exposure",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Drug Eras",
    routeName: "domainTable",
    domain: "drug_era",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Visit Occurrence",
    routeName: "domainTable",
    domain: "visit_occurrence",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Visit Detail",
    routeName: "domainTable",
    domain: "visit_detail",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Measurements",
    routeName: "domainTable",
    domain: "measurement",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Observations",
    routeName: "domainTable",
    domain: "observation",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Procedures",
    routeName: "domainTable",
    domain: "procedure_occurrence",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Device Exposures",
    routeName: "domainTable",
    domain: "device_exposure",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Death",
    routeName: "death",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Unmapped Source Codes",
    routeName: "unmappedSourceCodes",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-table",
    name: "Temporal Characterization",
    routeName: "temporalCharacterization",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-speedometer",
    name: "Performance",
    routeName: "performance",
  },
  {
    folder: "Data Source Release",
    icon: "mdi-alpha-m-circle-outline",
    name: "Metadata",
    routeName: "metadata",
  },
  {
    folder: "Data Network",
    icon: "mdi-table",
    name: "Overview",
    routeName: "overview",
  },
  {
    folder: "Data Network",
    icon: "mdi-sigma-lower",
    name: "Quality Assessment",
    routeName: "networkDataQuality",
  },
  {
    folder: "Data Network",
    icon: "mdi-chart-line",
    name: "Population Overview",
    routeName: "population",
  },
  {
    folder: "Data Network",
    icon: "mdi-dna",
    name: "Data Strand Report",
    routeName: "dataStrandReport",
  },
  {
    folder: "Data Network",
    icon: "mdi-table",
    name: "Unmapped Source Codes",
    routeName: "networkUnmappedSourceCodes",
  },
];
