import NetworkDataQualityIssuesByCdmTable from "@/pages/reports/network/NetworkDataQualitySummary/charts/NetworkDataQualityIssuesByCdmTable/NetworkDataQualityIssuesByCdmTable.vue";

export default NetworkDataQualityIssuesByCdmTable;
