import NetworkDataQualityIssuesByCategory from "@/pages/reports/network/NetworkDataQualitySummary/charts/NetworkDataQualityIssuesByCategory/NetworkDataQualityIssuesByCategory.vue";

export default NetworkDataQualityIssuesByCategory;
